//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssuerAccount.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IssuerAccountEntities : DbContext
    {
        public IssuerAccountEntities()
            : base("name=IssuerAccountEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<AccountOpeningApplication> AccountOpeningApplication { get; set; }
        public virtual DbSet<Deal> Deal { get; set; }
        public virtual DbSet<Investor> Investor { get; set; }
        public virtual DbSet<Issuer> Issuer { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<Registrar> Registrar { get; set; }
        public virtual DbSet<Security> Security { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
