//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssuerAccount.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public Nullable<int> Id_Investor { get; set; }
        public Nullable<int> Id_Issuer { get; set; }
        public string Text { get; set; }
    
        public virtual Investor Investor { get; set; }
        public virtual Issuer Issuer { get; set; }
    }
}
